### ISSUE TITLE
google adsense code will not display

### ISSUE THREAD

**Issue by hijak** [DTrejo/neo-proxy#2]
Hi

first off what an excellent idea!

but im having issues with my google adsense code not displaying
`<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><ins class="adsbygoogle" style="display:inline-block;width:728px;height:90px" data-ad-client="ca-pub-BLAH" data-ad-slot="BLAH"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script>`

just leaves a blank space

any ideas?

**Comment by DTrejo** [comment]
Wahoo someone is using it and likes it!

Some ideas about why it isn't working:
- AdSense might not like displaying on local host
- it might not like to display on your local IP
- it might only like to display on the domain you configured for it
- your adblocker is turned on
- ???

Can you think of anything else?

The neo proxy code is very short, I recommend you read it, especially the
part where it sets the host header, that is where the magic happens.

Cheers,
D

**Comment by hijak** [comment]
i managed to get it working piping it through a nginx reverse proxy?! anyway thats working now

but with one of the sites i reverse to i am getting

```
http://localhost:2010 -> https://kickass.to, hrefs kat.proxy

Error: socket hang up
    at createHangUpError (http.js:1476:15)
    at CleartextStream.socketCloseListener (http.js:1526:23)
    at CleartextStream.emit (events.js:95:17)
    at tls.js:693:10
    at process._tickCallback (node.js:419:13)
```

and the transform is not happening altho it does return the proxied site!?

**Comment by DTrejo** [comment]
Hmm okay well I'm glad you got something to work.

Are you sure that the search string is being found? Sadly there is no debug
mode, but you could put a console.log in the spot where it does the
find/replace.

Cheers man,
D

i managed to get it working piping it through a nginx reverse proxy?!
anyway thats working now

but with one of the sites i reverse to i am getting

http://localhost:2010 -> https://kickass.to, hrefs kat.proxy

Error: socket hang up
    at createHangUpError (http.js:1476:15)
    at CleartextStream.socketCloseListener (http.js:1526:23)
    at CleartextStream.emit (events.js:95:17)
    at tls.js:693:10
    at process._tickCallback (node.js:419:13)

and the transform is not happening altho it does return the proxied site!?

**Comment by hijak** [comment]
thanks for getting back to me ill try a few different ways :)

**Comment by DTrejo** [comment]
Good luck! Don't hesitate to ask more questions, but also remember the code
is so short, you've got the power!

D
